version: "2.1"
services:
  st2:
    build:
      context: ./stackstorm
      args:
        ST2_VERSION: ${ST2_VERSION}-${ST2_REVISION}
        ST2_REPO: ${ST2_REPO}
    image: st2

  api:
    build:
      context: ./st2api
    image: stackstorm/st2api:${ST2_VERSION}
    links:
      - mongo
      - rabbitmq
    volumes_from:
      - data

  auth:
    build:
      context: ./st2auth
    image: stackstorm/st2auth:${ST2_VERSION}
    links:
      - api
      - mongo
    volumes_from:
      - data

  stream:
    build:
      context: ./st2stream
    image: stackstorm/st2stream:${ST2_VERSION}
    links:
      - mongo
      - rabbitmq
    volumes_from:
      - data

  notifier:
    build:
      context: ./st2notifier
    image: stackstorm/st2notifier:${ST2_VERSION}
    links:
      - api
      - mongo
      - rabbitmq
    volumes_from:
      - data

  resultstracker:
    build:
      context: ./st2resultstracker
    image: stackstorm/st2resultstracker:${ST2_VERSION}
    links:
      - api
      - mongo
      - rabbitmq
    volumes_from:
      - data

  rulesengine:
    build:
      context: ./st2rulesengine
    image: stackstorm/st2rulesengine:${ST2_VERSION}
    links:
      - api
      - mongo
      - rabbitmq
    volumes_from:
      - data

  sensorcontainer:
    build:
      context: ./st2sensorcontainer
    image: stackstorm/st2sensorcontainer:${ST2_VERSION}
    links:
      - api
      - mongo
      - rabbitmq
    volumes_from:
      - data

  garbagecollector:
    build:
      context: ./st2garbagecollector
    image: stackstorm/st2garbagecollector:${ST2_VERSION}
    links:
      - api
      - mongo
      - rabbitmq
    volumes_from:
      - data

  actionrunner:
    build:
      context: ./st2actionrunner
    image: stackstorm/st2actionrunner:${ST2_VERSION}
    links:
      - api
      - auth
      - mongo
      - rabbitmq
    volumes_from:
      - data

  ## External Services
  mongo:
    image: mongo

  rabbitmq:
    image: rabbitmq

  ## Data container
  data:
    build: ./data
    volumes:
      - /etc/st2
      - /opt/stackstorm
    links:
      - rabbitmq
      - mongo

  ## Client container
  client:
    build: ./client
    links:
      - api
      - auth
